- name: download the version of python specified in the group_vars/target.yml
  uri:
    url: "{{ python_src_url }}"
    dest: /tmp/Python-{{ python_version }}.tgz
  args:
    creates: /tmp/Python-{{ python_version }}.tgz

- name: extract the downloaded python archive
  shell: /usr/bin/tar xzf /tmp/Python-{{ python_version }}.tgz
  args:
    creates: /tmp/Python-{{ python_version }}

- name: compile the python source
  shell: /usr/bin/cd /tmp/Python-{{ python_version }} && ./configure --enable-optimizations && make altinstall

- name: ensure pip is up-to-date
  shell: /usr/local/bin/pip{{ python_major_version }} install --upgrade pip

- name: remove the files we created
  shell: /usr/bin/rm -rf /tmp/Python-{{ python_version }}.tgz && /usr/bin/rm -rf /tmp/Python-{{ python_version }}