python_major_version: 3.9
python_minor_version: 12
python_version: "{{ python_major_version }}.{{ python_minor_version }}"
python_src_url: https://www.python.org/ftp/python/{{ python_version }}/Python-{{ python_version }}.tgz

layers:
  - pandas
  - numpy
  - psycopg2
  - sqlalchemy